---
- name: Configure Paper Social Server
  hosts: all
  become: true
  vars:
    aws_region: ap-south-1
    cloudwatch_agent_version: latest

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    # ✅ Install unzip (required for AWS CLI zip extraction)
    - name: Install unzip package
      apt:
        name: unzip
        state: present

    # ✅ Install AWS CLI v2 manually
    - name: Download AWS CLI v2 installer
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI v2
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    # ✅ Install CloudWatch Agent
    - name: Download CloudWatch agent
      get_url:
        url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/{{ cloudwatch_agent_version }}/amazon-cloudwatch-agent.deb"
        dest: /tmp/amazon-cloudwatch-agent.deb
        mode: '0755'

    - name: Install CloudWatch agent
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
        state: present

    - name: Create CloudWatch agent config directory
      file:
        path: /opt/aws/amazon-cloudwatch-agent/etc
        state: directory
        mode: '0755'

    - name: Configure CloudWatch agent
      template:
        src: templates/amazon-cloudwatch-agent.json.j2
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        mode: '0644'

    - name: Start CloudWatch agent
      systemd:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes

    - name: Verify CloudWatch agent status
      command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a status
      register: cloudwatch_status
      changed_when: false

    - name: Display CloudWatch agent status
      debug:
        var: cloudwatch_status.stdout_lines
